CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Enable ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Bootloader mode
CONFIG_ZMK_DBL_TAP_BOOTLOADER=y
